const byId=id=>document.getElementById(id);let statusData=null;let selectedPlatform='linux';
const formatRate=value=>{const units=['B/s','KB/s','MB/s','GB/s','TB/s'];let number=Number(value)||0;let index=0;while(number>=1000&&index<units.length-1){number/=1000;index++}return {number:number.toFixed(index===0?0:number<10?1:0),unit:units[index]}};
const ago=value=>{if(!value)return '—';const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<2)return 'now';if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;return `${Math.floor(seconds/3600)}h ago`};
const shortId=value=>value&&value.length>13?`${value.slice(0,8)}…${value.slice(-4)}`:value||'—';
const dateTime=value=>value?new Date(value).toLocaleString():'—';
function render(data){statusData=data;const uploadRate=formatRate(data.traffic.payloadBytesPerSecond);byId('state').textContent=(data.state||'unknown').toUpperCase();byId('state-dot').className=`dot ${data.state||''}`;byId('aircraft').textContent=data.source.aircraft??'—';byId('aircraft-note').textContent=data.source.aircraft==null?'Not reported by local decoder':`Seen during the last minute`;byId('rate').textContent=Number(data.traffic.messagesPerSecond||0).toFixed(1);byId('last-frame').textContent=ago(data.source.lastFrameAt);byId('source').textContent=`${(data.source.format||data.source.mode).toUpperCase()} · ${data.source.host}:${data.source.port}`;byId('upload-rate').textContent=uploadRate.number;byId('upload-unit').textContent=uploadRate.unit;byId('account').textContent=data.accountDisplay||'Not supplied';byId('installation').textContent=shortId(data.installationId);byId('installation').title=data.installationId||'';byId('connected').textContent=dateTime(data.connectedAt);byId('version').textContent=data.version||'—';byId('error').textContent=data.error||'';byId('error').classList.toggle('hidden',!data.error);byId('update-button').classList.toggle('hidden',!data.update.available);byId('latest-version').textContent=data.update.latestVersion||'';renderCommand()}
function renderCommand(){if(!statusData)return;byId('update-command').textContent=selectedPlatform==='linux'?statusData.update.linuxCommand:statusData.update.windowsCommand;byId('linux-tab').classList.toggle('selected',selectedPlatform==='linux');byId('windows-tab').classList.toggle('selected',selectedPlatform==='windows')}
async function refresh(){try{const response=await fetch('/api/status',{cache:'no-store'});if(response.ok)render(await response.json())}catch{byId('state').textContent='STATUS UNAVAILABLE';byId('state-dot').className='dot disconnected'}}
byId('update-button').addEventListener('click',()=>byId('update-dialog').showModal());byId('linux-tab').addEventListener('click',()=>{selectedPlatform='linux';renderCommand()});byId('windows-tab').addEventListener('click',()=>{selectedPlatform='windows';renderCommand()});byId('copy-command').addEventListener('click',async()=>{const command=byId('update-command').textContent;try{await navigator.clipboard.writeText(command);byId('copy-command').textContent='COPIED'}catch{const range=document.createRange();range.selectNodeContents(byId('update-command'));getSelection().removeAllRanges();getSelection().addRange(range);byId('copy-command').textContent='SELECTED'}setTimeout(()=>byId('copy-command').textContent='COPY COMMAND',1500)});refresh();setInterval(refresh,2000);
